version: "3.7"

services:
  database:
    image: postgres
    container_name: pgdatabase
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx-node
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - pgdatabase
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
